name = "AsymptoticBoltzmann"
uuid = "a88bca1c-88ca-4d82-8104-e76a8cd07798"
authors = ["Logan A Morrison <loanmorr@ucsc.com> and contributors"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
JuliaFormatter = "0.7, 0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
